-- Spec 064 — catálogo completo (copia FDB). Sin FACTURACION_*.
SET LIST ON;

SELECT CODIGO, DESCRIPCION, TVENTA, PCOSTO, PVENTA, MAYOREO, DEPT,
       DINVENTARIO, DINVMINIMO, DINVMAXIMO, PORCENTAJE_GANANCIA,
       COMPONENTES, IMPUESTOS
FROM PRODUCTOS
ORDER BY CODIGO;
