-- Spec 064 — queries mínimas contra COPIA del FDB (Firebird 2.5 / ODS 10.1).
-- Esquema real (isql 2026-08-31): PK PRODUCTOS = CODIGO; no hay ID, PFINAL ni ELIMINADO_EN.
-- Precio cajero = PVENTA. Stock = DINVENTARIO. Kits = COMPONENTES.
-- NO ejecutar sobre el archivo en uso de eleventa.
-- NO seleccionar FACTURACION_CERTIFICADOS ni blobs de CSD/FIEL.

SET LIST ON;

SELECT 'PRODUCTOS' AS TABLA, COUNT(*) AS N FROM PRODUCTOS;
SELECT 'VENTATICKETS' AS TABLA, COUNT(*) AS N FROM VENTATICKETS;
SELECT 'VENTATICKETS_ARTICULOS' AS TABLA, COUNT(*) AS N FROM VENTATICKETS_ARTICULOS;
SELECT 'CLIENTES' AS TABLA, COUNT(*) AS N FROM CLIENTES;
SELECT 'HISTORIAL_INVENTARIO' AS TABLA, COUNT(*) AS N FROM HISTORIAL_INVENTARIO;
SELECT 'PRODUCTOS_BASE' AS TABLA, COUNT(*) AS N FROM PRODUCTOS_BASE;
SELECT 'KITS_COMPONENTES' AS TABLA, COUNT(*) AS N FROM PRODUCTOS WHERE COMPONENTES IS NOT NULL AND COMPONENTES <> '';
SELECT 'LINEAS_CON_COMPONENTES' AS TABLA, COUNT(*) AS N FROM VENTATICKETS_ARTICULOS WHERE COMPONENTES IS NOT NULL AND COMPONENTES <> '';

SHOW TABLES;
SHOW TABLE PRODUCTOS;
SHOW TABLE VENTATICKETS;
SHOW TABLE VENTATICKETS_ARTICULOS;
SHOW TABLE IMPUESTOS;
SHOW TABLE DEPTS;
SHOW TABLE DEPARTAMENTOS;
SHOW TABLE PRODUCTOS_BASE;

SELECT FIRST 20 CODIGO, DESCRIPCION, TVENTA, PCOSTO, PVENTA, MAYOREO, DEPT, DINVENTARIO, PORCENTAJE_GANANCIA, COMPONENTES, IMPUESTOS
FROM PRODUCTOS
ORDER BY CODIGO;
